services:
  vite:
    image: atheken/vite-dev
    ports:
      - 5173:5173
      - 4173:4173
    expose:
      - 5173
      - 4173
    volumes:
      - .:/data
    entrypoint: "/start npm run build"
  cncjs:
    build: ./cncjs/container
    volumes:
      - ./cncjs:/root
      - ./dist:/root/dist
    depends_on:
      - grbl-sim
    ports:
      - 8000:8000
  grbl-sim:
    platform: linux/amd64
    image: atheken/grbl-sim
    expose:
      - 9600