services:
  vite:
    image: atheken/vite-dev
    ports:
      - 5173:5173
    expose:
      - 5173
    volumes:
      - .:/data
    entrypoint: '/start npm run dev'
  cncjs:
    build: ./cncjs/container
    volumes:
      - ./cncjs:/root
    depends_on:
      - grbl-sim
    restart: always
    ports:
      - 8000:8000
  grbl-sim:
    platform: linux/amd64
    environment:
      SIM_COUNT: 2
      GRBL_COMMENT: ''
      GRBL_REALTIME_FACTOR: 1.0
      GRBL_TIME_STEP: 1.0
      GRBL_ARGS: '-n'
    deploy:
      mode: replicated
      replicas: 2
    image: atheken/grbl-sim
    restart: always
    expose:
      - 9600
